### ISSUE TITLE
[한글] 뇌를 자극하는 Java

### ISSUE THREAD

**Issue by no-member** [no-member/study#29]
**GOAL**
회사다니고 싶냐? 자바를 배워라 🥲

**TODO**
- [x] 레거시 코드들을 쉽게 파악할 수 있도록 연습해라

**INDEX**
- [x] 제1장 자바 시작하기
- [x] 제2장 자바의 기초 문법
- [x] 제3장 프리미티브 타입
- [x] 제4장 연산자
- [x] 제5장 객체와 클래스
- [x] 제6장 상속과 인터페이스
- [x] 제7장 레퍼런스 타입
- [x] 제8장 패키지와 접근 제어
- [x] 제9장 기초적인 자바 클래스들
- [x] 제10장 파일 입출력에 사용되는 자바 클래스들
- [x] 제11장 Object 클래스
- [x] 제12장 Wrapper 클래스
- [x] 제13장 자료구조로 사용되는 자바 클래스들
- [x] 제14장 System 클래스
- [x] 제15장 익셉션 클래스
- [x] 제16장 네스티드 클래스와 네스티드 인터페이스
- [x] 제17장 객체의 직렬화
- [x] 제18장 멀티스레드 프로그래밍
- [x] 제19장 GUI 프로그래밍
- [x] 제20장 네트워크 통신 프로그래밍
- [x] 제21장 JDBC 프로그래밍
- [x] 제22장 애플릿 프로그래밍
