### ISSUE TITLE
[日本語] Land of Lisp

### ISSUE THREAD

**Issue by no-member** [no-member/study#36]
**GOAL**
俺はLisperになる！

**TODO**

- [ ] CLISPでプログラミングをする方法を学ぶこと
- [x] [MV](https://www.youtube.com/watch?v=HM1Zb3xmvMc)

**INDEX**
- [x] 1章 さあLispを始めてみよう
- [x] 2章 はじめてのLispプログラム
- [x] 3章 Lispの構文の世界を探検する
- [ ] 4章 条件と判断
- [ ] 5章 テキストゲームのエンジンを作る
- [ ] 6章 世界とのインタフェース: Lispでのデータの読み書き
- [ ] 7章 単純なリストの先へ
- [ ] 8章 親父のワンプスとは一味違う
- [ ] 9章 より進んだデータ型とジェネリックプログラミング
- [ ] 10章 loopコマンドによるループ
- [ ] 11章 format関数でテキストを表示する
- [ ] 12章 ストリーム
- [ ] 13章 Webサーバを作ろう!
- [ ] 14章 関数型プログラミングでLispをレベルアップ
- [ ] 15章 ダイス・オブ・ドゥーム：関数型スタイルでゲームを書こう
- [ ] 16章 マクロの魔法
- [ ] 17章 ドメイン特化言語
- [ ] 18章 遅延プログラミング
- [ ] 19章 ダイス・オブ・ドゥームに
- [ ] 20章 ダイス・オブ・ドゥームをさらに面白く
